SYMBOL = "XAUUSD"
LABEL = "Gold (XAU) / USD"

PRIMARY_INTERVAL = "1min"
PLOT_WINDOW_MINUTES = 15
ANALYSIS_LOOKBACK_1M = 720
CHART_DPI = 260

FETCH_CANDLES_EVERY_SECONDS = 60
POST_EVERY_MINUTES = 15
SIGNAL_EVAL_EVERY_SECONDS = 60
NEWS_POLL_EVERY_SECONDS = 180
MACRO_POLL_EVERY_SECONDS = 300

TRADE_MIN_CONF = 82
TRADE_COOLDOWN_SEC = 1800
TRADE_NOVELTY_PX = 0.0012

TP1_R = 1.5
TP2_R = 2.5

NEWS_ENABLED = True
MACRO_ENABLED = True
NEWS_MAX_ITEMS = 8
NEWS_RELEVANCE_MIN = 0.20
